import { ChargingStation, ConnectorType } from '../types';

// Demo charging stations around Chhatrapati Sambhajinagar (Aurangabad), Maharashtra
export const demoStations: ChargingStation[] = [
  {
    id: 'demo-1',
    name: 'FastCharge Hub - CIDCO',
    operator: 'Tata Power EZ Charge',
    address: 'CIDCO Bus Stand, Chhatrapati Sambhajinagar',
    latitude: 19.8828,
    longitude: 75.3285,
    power: 120,
    connectors: ['CCS2', 'Type2'] as ConnectorType[],
    availableChargers: 5,
    totalChargers: 8,
    pricePerKwh: 16,
    isOpen24h: true,
    openingHours: 'Open 24 hours',
    rating: 4.5,
    lastUpdated: '2024-01-15T10:30:00Z',
    dataSource: 'Demo Data',
    isDemo: true,
  },
  {
    id: 'demo-2',
    name: 'GreenCharge Station - Railway Station',
    operator: 'Ather Grid',
    address: 'Near Railway Station, Chhatrapati Sambhajinagar',
    latitude: 19.8795,
    longitude: 75.3410,
    power: 60,
    connectors: ['Type2', 'CCS2'] as ConnectorType[],
    availableChargers: 2,
    totalChargers: 4,
    pricePerKwh: 14,
    isOpen24h: false,
    openingHours: '6:00 AM - 11:00 PM',
    rating: 4.2,
    lastUpdated: '2024-01-15T09:00:00Z',
    dataSource: 'Demo Data',
    isDemo: true,
  },
  {
    id: 'demo-3',
    name: 'UltraCharge Mall',
    operator: 'ChargeZone',
    address: 'Prozone Mall, Nirala Bazar, Chhatrapati Sambhajinagar',
    latitude: 19.8860,
    longitude: 75.3520,
    power: 150,
    connectors: ['CCS2', 'CHAdeMO', 'Type2'] as ConnectorType[],
    availableChargers: 6,
    totalChargers: 10,
    pricePerKwh: 18,
    isOpen24h: true,
    openingHours: 'Open 24 hours',
    rating: 4.7,
    lastUpdated: '2024-01-15T11:00:00Z',
    dataSource: 'Demo Data',
    isDemo: true,
  },
  {
    id: 'demo-4',
    name: 'EcoCharge Highway',
    operator: 'Indian Oil',
    address: 'NH-52 Highway, Chhatrapati Sambhajinagar',
    latitude: 19.8650,
    longitude: 75.3600,
    power: 50,
    connectors: ['CCS2', 'CHAdeMO'] as ConnectorType[],
    availableChargers: 1,
    totalChargers: 3,
    pricePerKwh: 12,
    isOpen24h: true,
    openingHours: 'Open 24 hours',
    rating: 3.8,
    lastUpdated: '2024-01-14T16:00:00Z',
    dataSource: 'Demo Data',
    isDemo: true,
  },
  {
    id: 'demo-5',
    name: 'PowerUp Arena',
    operator: 'ElectreeFi',
    address: 'Krishi Vallabh Bhavan Road, Chhatrapati Sambhajinagar',
    latitude: 19.8720,
    longitude: 75.3350,
    power: 25,
    connectors: ['Type2'] as ConnectorType[],
    availableChargers: 3,
    totalChargers: 4,
    pricePerKwh: 10,
    isOpen24h: false,
    openingHours: '7:00 AM - 10:00 PM',
    rating: 4.0,
    lastUpdated: '2024-01-15T08:00:00Z',
    dataSource: 'Demo Data',
    isDemo: true,
  },
  {
    id: 'demo-6',
    name: 'VoltStation University',
    operator: 'State Power Corp',
    address: 'Dr. Babasaheb Ambedkar Road, Chhatrapati Sambhajinagar',
    latitude: 19.8690,
    longitude: 75.3200,
    power: 80,
    connectors: ['CCS2', 'Type2'] as ConnectorType[],
    availableChargers: 0,
    totalChargers: 4,
    pricePerKwh: 15,
    isOpen24h: false,
    openingHours: '8:00 AM - 9:00 PM',
    rating: 3.5,
    lastUpdated: '2024-01-15T07:30:00Z',
    dataSource: 'Demo Data',
    isDemo: true,
  },
  {
    id: 'demo-7',
    name: 'ChargePoint Express',
    operator: 'Exicom',
    address: 'Paithan Road, Chhatrapati Sambhajinagar',
    latitude: 19.8900,
    longitude: 75.3450,
    power: 180,
    connectors: ['CCS2', 'CHAdeMO', 'Type2'] as ConnectorType[],
    availableChargers: 7,
    totalChargers: 12,
    pricePerKwh: 20,
    isOpen24h: true,
    openingHours: 'Open 24 hours',
    rating: 4.8,
    lastUpdated: '2024-01-15T12:00:00Z',
    dataSource: 'Demo Data',
    isDemo: true,
  },
  {
    id: 'demo-8',
    name: 'QuickCharge Plaza',
    operator: 'Delta Electronics',
    address: 'Jalna Road, Chhatrapati Sambhajinagar',
    latitude: 19.8750,
    longitude: 75.3550,
    power: 60,
    connectors: ['CCS2', 'Type2'] as ConnectorType[],
    availableChargers: 3,
    totalChargers: 6,
    pricePerKwh: 14,
    isOpen24h: false,
    openingHours: '5:00 AM - 12:00 AM',
    rating: 4.1,
    lastUpdated: '2024-01-15T10:00:00Z',
    dataSource: 'Demo Data',
    isDemo: true,
  },
  {
    id: 'demo-9',
    name: 'MegaCharge Station',
    operator: 'ABB',
    address: 'Beed Bypass, Chhatrapati Sambhajinagar',
    latitude: 19.8580,
    longitude: 75.3480,
    power: 350,
    connectors: ['CCS2', 'CHAdeMO'] as ConnectorType[],
    availableChargers: 4,
    totalChargers: 6,
    pricePerKwh: 22,
    isOpen24h: true,
    openingHours: 'Open 24 hours',
    rating: 4.9,
    lastUpdated: '2024-01-15T11:30:00Z',
    dataSource: 'Demo Data',
    isDemo: true,
  },
  {
    id: 'demo-10',
    name: 'CityCharge Center',
    operator: 'Fortum',
    address: 'Osmanpura, Chhatrapati Sambhajinagar',
    latitude: 19.8810,
    longitude: 75.3380,
    power: 22,
    connectors: ['Type2'] as ConnectorType[],
    availableChargers: 2,
    totalChargers: 3,
    pricePerKwh: 8,
    isOpen24h: false,
    openingHours: '6:00 AM - 11:00 PM',
    rating: 3.9,
    lastUpdated: '2024-01-15T09:30:00Z',
    dataSource: 'Demo Data',
    isDemo: true,
  },
  // Stations along Pune route
  {
    id: 'demo-11',
    name: 'HighwayCharge Ahmednagar',
    operator: 'Tata Power',
    address: 'NH-753, Ahmednagar',
    latitude: 19.0915,
    longitude: 74.7383,
    power: 120,
    connectors: ['CCS2', 'CHAdeMO', 'Type2'] as ConnectorType[],
    availableChargers: 4,
    totalChargers: 8,
    pricePerKwh: 16,
    isOpen24h: true,
    openingHours: 'Open 24 hours',
    rating: 4.3,
    lastUpdated: '2024-01-15T10:00:00Z',
    dataSource: 'Demo Data',
    isDemo: true,
  },
  {
    id: 'demo-12',
    name: 'PuneExpress Charger',
    operator: 'ChargeZone',
    address: 'Shirur, Pune District',
    latitude: 18.8150,
    longitude: 74.3900,
    power: 150,
    connectors: ['CCS2', 'Type2'] as ConnectorType[],
    availableChargers: 5,
    totalChargers: 8,
    pricePerKwh: 17,
    isOpen24h: true,
    openingHours: 'Open 24 hours',
    rating: 4.6,
    lastUpdated: '2024-01-15T11:00:00Z',
    dataSource: 'Demo Data',
    isDemo: true,
  },
  {
    id: 'demo-13',
    name: 'Pune Central Charge',
    operator: 'Ather Grid',
    address: 'Shivajinagar, Pune',
    latitude: 18.5204,
    longitude: 73.8567,
    power: 100,
    connectors: ['CCS2', 'Type2', 'CHAdeMO'] as ConnectorType[],
    availableChargers: 3,
    totalChargers: 6,
    pricePerKwh: 18,
    isOpen24h: true,
    openingHours: 'Open 24 hours',
    rating: 4.4,
    lastUpdated: '2024-01-15T12:00:00Z',
    dataSource: 'Demo Data',
    isDemo: true,
  },
  // Mumbai route stations
  {
    id: 'demo-14',
    name: 'Nashik Highway Charge',
    operator: 'Indian Oil',
    address: 'NH-160, Sinnar',
    latitude: 19.9300,
    longitude: 73.9200,
    power: 60,
    connectors: ['CCS2', 'Type2'] as ConnectorType[],
    availableChargers: 2,
    totalChargers: 4,
    pricePerKwh: 14,
    isOpen24h: true,
    openingHours: 'Open 24 hours',
    rating: 4.0,
    lastUpdated: '2024-01-15T09:00:00Z',
    dataSource: 'Demo Data',
    isDemo: true,
  },
  {
    id: 'demo-15',
    name: 'Mumbai Gateway Charger',
    operator: 'Tata Power',
    address: 'Andheri East, Mumbai',
    latitude: 19.1136,
    longitude: 72.8697,
    power: 200,
    connectors: ['CCS2', 'CHAdeMO', 'Type2'] as ConnectorType[],
    availableChargers: 6,
    totalChargers: 10,
    pricePerKwh: 20,
    isOpen24h: true,
    openingHours: 'Open 24 hours',
    rating: 4.7,
    lastUpdated: '2024-01-15T11:00:00Z',
    dataSource: 'Demo Data',
    isDemo: true,
  },
];

export function getDemoStations(): ChargingStation[] {
  return demoStations;
}

export function getDemoStationsNearby(lat: number, lng: number, radiusKm: number = 50): ChargingStation[] {
  const R = 6371;
  return demoStations.filter(station => {
    const dLat = (station.latitude - lat) * Math.PI / 180;
    const dLon = (station.longitude - lng) * Math.PI / 180;
    const a = Math.sin(dLat / 2) * Math.sin(dLat / 2) +
      Math.cos(lat * Math.PI / 180) * Math.cos(station.latitude * Math.PI / 180) *
      Math.sin(dLon / 2) * Math.sin(dLon / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    const distance = R * c;
    return distance <= radiusKm;
  });
}
